CREATE DATABASE IF NOT EXISTS agendamentobd;

USE agendamentobd;

CREATE TABLE IF NOT EXISTS agendamentoemail (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
    assunto VARCHAR(255) NOT NULL,
    mensagem VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    enviado BOOLEAN NOT NULL
);
